version: '3.8'

services:
  koreader-sync:
    build: .
    container_name: koreader-sync
    restart: unless-stopped
    ports:
      - "8742:8742"
    volumes:
      - ./koreader.db:/app/koreader.db
